Permissions fix
RedTurtle/redturtle.prenotazioni pull request #106
Opened 2023-10-17 15:33 UTC by folix-01

2023-10-19 12:18 UTC, cekk requested changes
Nel README c'è scritto che c'è un ruolo nuovo (Bookings Manager) e che cosa può fare?

2023-10-19 12:18 UTC, cekk commented on src/redturtle/prenotazioni/profiles/default/rolemap.xml
> +    <permission name="Review portal content" acquire="True">
questo permesso lo metterei nel workflow e non qui.
Se lo metti nella rolemap, stai dando questo permesso ai Bookings Manager su tutti i contenuti del sito

2023-10-19 12:18 UTC, cekk commented on src/redturtle/prenotazioni/upgrades.py
> +    for brain in api.portal.get_tool("portal_catalog")(portal_type="Prenotazione"):
api.portal.get_tool("portal_catalog")(portal_type="Prenotazione") => api.content.find(portal_type="Prenotazione")

2023-10-19 15:30 UTC, folix-01 commented on src/redturtle/prenotazioni/upgrades.py
> +    for brain in api.portal.get_tool("portal_catalog")(portal_type="Prenotazione"):
Solved

2023-10-20 08:09 UTC, cekk commented
sistema i test e per me è ok

2023-10-20 13:08 UTC, merged