Booking code searchable
RedTurtle/redturtle.prenotazioni pull request #153
Opened 2023-12-18 15:38 UTC by folix-01

2023-12-18 15:44 UTC, cekk requested changes

2023-12-18 15:44 UTC, cekk commented on CHANGES.rst
> +- Add the booking code to SearchableText index.
Scrivi da quale pr/commit del master l'hai inserito

2023-12-18 15:44 UTC, cekk commented on src/redturtle/prenotazioni/upgrades.py
> +    for brain in api.portal.get_tool("portal_catalog")(portal_type="Prenotazione"):
basta fare "api.content.find(portal_type="Prenotazione")"

2023-12-18 15:46 UTC, folix-01 commented on CHANGES.rst
> +- Add the booking code to SearchableText index.
Nonostante è un cherry-pick, rimane la modifica isolata di se. Riporto però non vedo il senso

2023-12-18 15:47 UTC, folix-01 commented on src/redturtle/prenotazioni/upgrades.py
> +    for brain in api.portal.get_tool("portal_catalog")(portal_type="Prenotazione"):
Mi piace di più chiamare il catalog esplicitamente

2023-12-19 09:14 UTC, cekk approved these changes

2023-12-19 09:14 UTC, merged