Bookign canceled manager email
RedTurtle/redturtle.prenotazioni pull request #188
Opened 2024-03-01 16:27 UTC by folix-01

2024-03-01 16:40 UTC, mamico commented
Aggiungiamo un test?

2024-03-01 16:42 UTC, folix-01 commented
> Aggiungiamo un test?

Questo modulo non è testato di se, sarebbe da farlo a parte come refactoring

2024-03-05 14:37 UTC, folix-01 commented on src/redturtle/prenotazioni/behaviors/booking_folder/notifications/email/events.py
> +    if not getattr(booking, "email_responsabile", []):
Done

2024-03-05 15:57 UTC, cekk requested changes

2024-03-05 15:57 UTC, cekk commented on src/redturtle/prenotazioni/behaviors/booking_folder/notifications/email/events.py
> +    if not getattr(booking, "email_responsabile", []):
non sarebbe più corretto prenderla direttamente dal bookingfolder?
L'acquisizione è comoda ma rischia di confondere. Dalla prenotazione si prende facilmente il folder, e il codice è più chiaro

2024-03-06 09:26 UTC, folix-01 commented on src/redturtle/prenotazioni/behaviors/booking_folder/notifications/email/events.py
> +    if not getattr(booking, "email_responsabile", []):
Done, but really i don’t think it is needed so as we use the technology, which is built over the zope, which uses Acquisition technology as well.

2024-03-07 11:22 UTC, merged