Notification failure history
RedTurtle/redturtle.prenotazioni pull request #201
Opened 2024-04-03 10:53 UTC by folix-01

2024-04-12 09:12 UTC, cekk requested changes
Manca l'upgrade-step per abilitare la behavior nelle prenotazioni.
Non caricare tutto il types_tool ma aggiungi a mano la behavior che serve

2024-04-12 09:12 UTC, cekk commented on src/redturtle/prenotazioni/profiles/default/workflows/prenotazioni_workflow/definition.xml
> +      <permission-role>Reader</permission-role>
Toglierei Owner e Reader, o servono?

2024-04-12 09:12 UTC, cekk commented on src/redturtle/prenotazioni/profiles/default/workflows/prenotazioni_workflow/definition.xml
> +      <permission-role>Owner</permission-role>
Idem qui

2024-04-12 09:12 UTC, cekk commented on src/redturtle/prenotazioni/profiles/default/workflows/prenotazioni_workflow/definition.xml
> +      <permission-role>Owner</permission-role>
Stessa cosa

2024-04-12 09:12 UTC, cekk commented on src/redturtle/prenotazioni/profiles/default/workflows/prenotazioni_workflow/definition.xml
> +      <permission-role>Owner</permission-role>
Anche qui

2024-04-12 09:12 UTC, cekk commented on src/redturtle/prenotazioni/profiles/default/workflows/prenotazioni_workflow/definition.xml
> +      <permission-role>Owner</permission-role>
..e qui

2024-04-12 09:50 UTC, folix-01 commented on src/redturtle/prenotazioni/profiles/default/workflows/prenotazioni_workflow/definition.xml
> +      <permission-role>Reader</permission-role>
solved

2024-04-12 09:50 UTC, folix-01 commented on src/redturtle/prenotazioni/profiles/default/workflows/prenotazioni_workflow/definition.xml
> +      <permission-role>Owner</permission-role>
solved

2024-04-12 09:50 UTC, folix-01 commented on src/redturtle/prenotazioni/profiles/default/workflows/prenotazioni_workflow/definition.xml
> +      <permission-role>Owner</permission-role>
solved

2024-04-12 09:50 UTC, folix-01 commented
> Manca l'upgrade-step per abilitare la behavior nelle prenotazioni. Non caricare tutto il types_tool ma aggiungi a mano la behavior che serve

done

2024-04-12 10:22 UTC, folix-01 commented on src/redturtle/prenotazioni/profiles/default/workflows/prenotazioni_workflow/definition.xml
> +      <permission-role>Owner</permission-role>
solved

2024-04-17 08:06 UTC, cekk requested changes

2024-04-17 08:06 UTC, cekk commented on src/redturtle/prenotazioni/upgrades.py
> +    update_types(context)
Questo è facile da fare a mano, ed è più safe: https://github.com/RedTurtle/design.plone.contenttypes/blob/main/src/design/plone/contenttypes/upgrades/upgrades.py#L1602

2024-04-17 09:31 UTC, folix-01 commented on src/redturtle/prenotazioni/upgrades.py
> +    update_types(context)
solved

2024-05-09 08:02 UTC, cekk commented on src/redturtle/prenotazioni/adapters/booker.py
> +        with api.env.adopt_roles(roles=["Manager"]):
ricordami perché devi diventare Manager

2024-05-13 07:04 UTC, folix-01 commented on src/redturtle/prenotazioni/adapters/booker.py
> +        with api.env.adopt_roles(roles=["Manager"]):
va buttato via questo branch

2024-05-13 07:04 UTC, closed without merging