Iocomuneioprenoto integration
RedTurtle/redturtle.prenotazioni pull request #27
Opened 2023-01-19 10:05 UTC by foxtrot-dfm1

2023-01-25 16:28 UTC, luca-bellenghi requested changes

2023-01-25 16:28 UTC, luca-bellenghi commented on src/redturtle/prenotazioni/content/prenotazioni_folder_container.py
> +        return False
Attenzione che qui deve essere True se dobbiamo escluderlo

2023-01-27 14:43 UTC, foxtrot-dfm1 commented on src/redturtle/prenotazioni/content/prenotazioni_folder_container.py
> +        return False
solved

2023-01-31 09:44 UTC, eikichi18 approved these changes

2023-02-01 09:46 UTC, merged