added field 'cosa_serve'
RedTurtle/redturtle.prenotazioni pull request #33
Opened 2023-04-06 15:35 UTC by daniele-andreotti

2023-04-07 09:36 UTC, cekk requested changes
Manca il changelog

2023-04-07 09:36 UTC, cekk commented on src/redturtle/prenotazioni/browser/templates/prenotazione.pt
> +                <div class="field">
lo farei condizionale questo: nel senso che se non è compilato, non lo mostro

2023-04-07 10:57 UTC, daniele-andreotti commented on src/redturtle/prenotazioni/browser/templates/prenotazione.pt
> +                <div class="field">
Fatto

2023-04-13 10:27 UTC, cekk commented
@daniele-andreotti sistema i conflitti e poi lo mergiamo

2023-04-18 20:46 UTC, cekk approved these changes

2023-04-18 20:47 UTC, merged