Manual confirm mail
RedTurtle/redturtle.prenotazioni pull request #92
Opened 2023-09-08 15:56 UTC by folix-01

2023-09-08 16:15 UTC, mamico requested changes

2023-09-08 16:15 UTC, mamico commented on src/redturtle/prenotazioni/restapi/services/booking/configure.zcml
> +      permission="cmf.ManagePortal"
manage portal ?

non devono poter richiamare l'api gli operatori ?

2023-09-08 16:15 UTC, mamico commented on src/redturtle/prenotazioni/restapi/services/booking/configure.zcml
> +      name="@booking_notify_about_confirm"
```suggestion
      name="@booking-notify"
```

2023-09-08 16:25 UTC, folix-01 commented on src/redturtle/prenotazioni/restapi/services/booking/configure.zcml
> +      permission="cmf.ManagePortal"
Confusione con il cmf.MangePortalContent

2023-09-09 07:38 UTC, mamico commented on src/redturtle/prenotazioni/restapi/services/booking/configure.zcml
> +      permission="cmf.ManagePortal"
`cmf.MangePortalContent` non esiste ... credo che qui il permesso giusto sia questo:
 https://github.com/RedTurtle/redturtle.prenotazioni/blob/master/src/redturtle/prenotazioni/permissions.zcml#L44

2023-09-10 16:46 UTC, folix-01 commented on src/redturtle/prenotazioni/restapi/services/booking/configure.zcml
> +      permission="cmf.ManagePortal"
Solved.

2023-09-11 10:40 UTC, merged